name: main

on: [push, pull_request]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Start demo database and qgis-server 2
        run: |
          cd tests/docker
          docker-compose up -d

      - name: Setting up python 3.6
        uses: actions/setup-python@v2
        with:
            python-version: '3.6'

      - name: Run unittests
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python test.py

    release:
      needs: test
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      steps:

      - name: Get the version from tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Create release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: false